### PR TITLE
Fixed getPhonebook when FB uses self-signed cert 

### PR DESCRIPTION
**Pull request by Khaos66**
The phonebook was not read, because of a self-signed cert in FB

### CODE REVIEW

**Comment by Apollon77** [comment]
But how an added "check that no data are there" will fix the issue?

**Comment by Khaos66** [comment]
Idk... It worked for me =D

**Comment by Apollon77** [comment]
ANd you got phonebook entries or were they just not there and thats why it works?

**Comment by Apollon77** [comment]
DOy ou still have the original error that was existing?

**Comment by Khaos66** [comment]
I get the phone book entries. It works correctly. 
I don't know the original error anymore. Sorry

**Comment by Apollon77** [comment]
aahh now I see ... seems I missed some changes in the PR on last view ... (maybe too late) ... got it now

BTW: what does "TAM" mean?

**Comment by Khaos66** [comment]
Glad it works out now.
TAM is from the official FritzBox docs. It means Telephone Answering Machine ;)

**Pull request merged**
